#!/usr/bin/env python3
"""Rebuild knowledge/INDEX.md for each layer of ~/ai from note frontmatter.

Usage:
    build_index.py                 # general, personal and current layers
    build_index.py ~/ai/personal   # only the given layer root(s)
    build_index.py --check         # exit 1 if any INDEX.md would change (for git hooks)

A note is any *.md under <layer>/knowledge/ except INDEX.md and README.md. Frontmatter is
the block between the first two '---' lines with `key: value` pairs; `tags` may be a
YAML flow list. Notes without frontmatter are listed separately so they get fixed.
"""
import argparse
import os
import re
import sys
from collections import defaultdict
from pathlib import Path

AI_ROOT = Path(os.environ.get("AI_ROOT", Path.home() / "ai"))
DEFAULT_LAYERS = ["general", "personal", "current"]
SKIP = {"INDEX.md", "README.md"}
DATE_RE = re.compile(r"^(\d{4}-\d{2}-\d{2})-")


def parse_frontmatter(text):
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return None, lines
    meta = {}
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            return meta, lines[i + 1:]
        if ":" in line:
            key, _, value = line.partition(":")
            value = value.strip()
            if value.startswith("[") and value.endswith("]"):
                value = [v.strip().strip("'\"") for v in value[1:-1].split(",") if v.strip()]
            meta[key.strip()] = value
    return None, lines


def first_heading(body):
    for line in body:
        if line.startswith("# "):
            return line[2:].strip()
    return None


def collect(knowledge):
    notes, missing = [], []
    for path in sorted(knowledge.rglob("*.md")):
        if path.name in SKIP or any(p.startswith(".") for p in path.parts):
            continue
        rel = path.relative_to(knowledge)
        meta, body = parse_frontmatter(path.read_text(encoding="utf-8", errors="replace"))
        title = first_heading(body) or path.stem
        if meta is None:
            missing.append((rel, title))
            continue
        m = DATE_RE.match(path.name)
        notes.append({
            "rel": rel,
            "title": title,
            "system": meta.get("system") or "unsorted",
            "status": meta.get("status") or "?",
            "checked": meta.get("checked") or "",
            "date": m.group(1) if m else "",
            "tags": meta.get("tags") if isinstance(meta.get("tags"), list) else [],
        })
    return notes, missing


def link(rel, title):
    return f"[{title}]({rel.as_posix()})"


def render(layer_name, notes, missing):
    out = [f"# Index: {layer_name}", "",
           "Generated by `general/scripts/build_index.py`. Do not edit by hand.", ""]
    systems = [n for n in notes if n["rel"].parts[0] == "systems"]
    log = [n for n in notes if n["rel"].parts[0] == "log"]
    other = [n for n in notes if n["rel"].parts[0] not in ("systems", "log")]

    if systems:
        out += ["## Systems", ""]
        for n in sorted(systems, key=lambda n: n["system"]):
            out.append(f"- {link(n['rel'], n['title'])} `{n['status']}` checked {n['checked']}")
        out.append("")

    if other:
        out += ["## Notes by topic", ""]
        by_topic = defaultdict(list)
        for n in other:
            by_topic[n["rel"].parts[0] if len(n["rel"].parts) > 1 else n["system"]].append(n)
        for topic in sorted(by_topic):
            out.append(f"### {topic}")
            out.append("")
            for n in sorted(by_topic[topic], key=lambda n: n["title"].lower()):
                tags = f" _{', '.join(n['tags'])}_" if n["tags"] else ""
                out.append(f"- {link(n['rel'], n['title'])} `{n['status']}` checked {n['checked']}{tags}")
            out.append("")

    if log:
        out += ["## Log (newest first)", ""]
        by_system = defaultdict(list)
        for n in log:
            by_system[n["system"]].append(n)
        for n in sorted(log, key=lambda n: (n["date"], n["rel"].name), reverse=True)[:30]:
            out.append(f"- {n['date']} `{n['system']}` {link(n['rel'], n['title'])}")
        out.append("")
        out += ["### Log by system", ""]
        for system in sorted(by_system):
            entries = sorted(by_system[system], key=lambda n: n["date"], reverse=True)
            out.append(f"- **{system}** ({len(entries)}): " + ", ".join(
                f"[{n['date']}]({n['rel'].as_posix()})" for n in entries[:8])
                + (" ..." if len(entries) > 8 else ""))
        out.append("")

    outdated = [n for n in notes if n["status"] == "outdated"]
    hypo = [n for n in notes if n["status"] == "hypothesis"]
    if hypo:
        out += ["## Open hypotheses", ""] + [f"- {link(n['rel'], n['title'])}" for n in hypo] + [""]
    if outdated:
        out += ["## Outdated", ""] + [f"- {link(n['rel'], n['title'])}" for n in outdated] + [""]
    if missing:
        out += ["## Missing frontmatter", "", "Add `system`, `status`, `checked` to these files.", ""]
        out += [f"- {link(rel, title)}" for rel, title in missing] + [""]
    if not notes and not missing:
        out += ["_No notes yet._", ""]
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("layers", nargs="*", help="layer roots (default: general, personal, current under ~/ai)")
    ap.add_argument("--check", action="store_true", help="do not write; exit 1 if any index is stale")
    args = ap.parse_args()

    roots = [Path(p).expanduser() for p in args.layers] or [AI_ROOT / l for l in DEFAULT_LAYERS]
    stale = 0
    for root in roots:
        knowledge = root / "knowledge"
        if not knowledge.is_dir():
            print(f"skip {root}: no knowledge/ directory", file=sys.stderr)
            continue
        notes, missing = collect(knowledge)
        text = render(root.resolve().name, notes, missing)
        target = knowledge / "INDEX.md"
        current = target.read_text(encoding="utf-8") if target.exists() else None
        if current == text:
            print(f"{target}: up to date ({len(notes)} notes)")
            continue
        stale += 1
        if args.check:
            print(f"{target}: stale")
        else:
            target.write_text(text, encoding="utf-8")
            print(f"{target}: written ({len(notes)} notes, {len(missing)} missing frontmatter)")
    return 1 if (args.check and stale) else 0


if __name__ == "__main__":
    sys.exit(main())
